//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace TG_BIN.wsAppDocSearch {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsAppDocSearchPortSoapBinding", Namespace="urn:DefaultNamespace")]
    public partial class wsAppDocSearchElement : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GETDEFAULTDBPATHOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETFORMLISTOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETEDMSLISTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SEARCHEDMSDOCOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsAppDocSearchElement() {
            this.Url = global::TG_BIN.Properties.Settings.Default.TG_BIN_wsAppDocSearch_wsAppDocSearchElement;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GETDEFAULTDBPATHCompletedEventHandler GETDEFAULTDBPATHCompleted;
        
        /// <remarks/>
        public event GETFORMLISTCompletedEventHandler GETFORMLISTCompleted;
        
        /// <remarks/>
        public event GETEDMSLISTCompletedEventHandler GETEDMSLISTCompleted;
        
        /// <remarks/>
        public event SEARCHEDMSDOCCompletedEventHandler SEARCHEDMSDOCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:DefaultNamespace", ResponseNamespace="urn:DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("GETDEFAULTDBPATHReturn")]
        public string GETDEFAULTDBPATH(string EMPNO) {
            object[] results = this.Invoke("GETDEFAULTDBPATH", new object[] {
                        EMPNO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETDEFAULTDBPATHAsync(string EMPNO) {
            this.GETDEFAULTDBPATHAsync(EMPNO, null);
        }
        
        /// <remarks/>
        public void GETDEFAULTDBPATHAsync(string EMPNO, object userState) {
            if ((this.GETDEFAULTDBPATHOperationCompleted == null)) {
                this.GETDEFAULTDBPATHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETDEFAULTDBPATHOperationCompleted);
            }
            this.InvokeAsync("GETDEFAULTDBPATH", new object[] {
                        EMPNO}, this.GETDEFAULTDBPATHOperationCompleted, userState);
        }
        
        private void OnGETDEFAULTDBPATHOperationCompleted(object arg) {
            if ((this.GETDEFAULTDBPATHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETDEFAULTDBPATHCompleted(this, new GETDEFAULTDBPATHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:DefaultNamespace", ResponseNamespace="urn:DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("GETFORMLISTReturn")]
        public string GETFORMLIST(string COMPANY) {
            object[] results = this.Invoke("GETFORMLIST", new object[] {
                        COMPANY});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETFORMLISTAsync(string COMPANY) {
            this.GETFORMLISTAsync(COMPANY, null);
        }
        
        /// <remarks/>
        public void GETFORMLISTAsync(string COMPANY, object userState) {
            if ((this.GETFORMLISTOperationCompleted == null)) {
                this.GETFORMLISTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETFORMLISTOperationCompleted);
            }
            this.InvokeAsync("GETFORMLIST", new object[] {
                        COMPANY}, this.GETFORMLISTOperationCompleted, userState);
        }
        
        private void OnGETFORMLISTOperationCompleted(object arg) {
            if ((this.GETFORMLISTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETFORMLISTCompleted(this, new GETFORMLISTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:DefaultNamespace", ResponseNamespace="urn:DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("GETEDMSLISTReturn")]
        public string GETEDMSLIST(string COMPANY) {
            object[] results = this.Invoke("GETEDMSLIST", new object[] {
                        COMPANY});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETEDMSLISTAsync(string COMPANY) {
            this.GETEDMSLISTAsync(COMPANY, null);
        }
        
        /// <remarks/>
        public void GETEDMSLISTAsync(string COMPANY, object userState) {
            if ((this.GETEDMSLISTOperationCompleted == null)) {
                this.GETEDMSLISTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETEDMSLISTOperationCompleted);
            }
            this.InvokeAsync("GETEDMSLIST", new object[] {
                        COMPANY}, this.GETEDMSLISTOperationCompleted, userState);
        }
        
        private void OnGETEDMSLISTOperationCompleted(object arg) {
            if ((this.GETEDMSLISTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETEDMSLISTCompleted(this, new GETEDMSLISTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:DefaultNamespace", ResponseNamespace="urn:DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("SEARCHEDMSDOCReturn")]
        public string SEARCHEDMSDOC(string DBPATH, string SEARCHFORM, string SEARCHSTRING) {
            object[] results = this.Invoke("SEARCHEDMSDOC", new object[] {
                        DBPATH,
                        SEARCHFORM,
                        SEARCHSTRING});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SEARCHEDMSDOCAsync(string DBPATH, string SEARCHFORM, string SEARCHSTRING) {
            this.SEARCHEDMSDOCAsync(DBPATH, SEARCHFORM, SEARCHSTRING, null);
        }
        
        /// <remarks/>
        public void SEARCHEDMSDOCAsync(string DBPATH, string SEARCHFORM, string SEARCHSTRING, object userState) {
            if ((this.SEARCHEDMSDOCOperationCompleted == null)) {
                this.SEARCHEDMSDOCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSEARCHEDMSDOCOperationCompleted);
            }
            this.InvokeAsync("SEARCHEDMSDOC", new object[] {
                        DBPATH,
                        SEARCHFORM,
                        SEARCHSTRING}, this.SEARCHEDMSDOCOperationCompleted, userState);
        }
        
        private void OnSEARCHEDMSDOCOperationCompleted(object arg) {
            if ((this.SEARCHEDMSDOCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SEARCHEDMSDOCCompleted(this, new SEARCHEDMSDOCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GETDEFAULTDBPATHCompletedEventHandler(object sender, GETDEFAULTDBPATHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETDEFAULTDBPATHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETDEFAULTDBPATHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GETFORMLISTCompletedEventHandler(object sender, GETFORMLISTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETFORMLISTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETFORMLISTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GETEDMSLISTCompletedEventHandler(object sender, GETEDMSLISTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETEDMSLISTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETEDMSLISTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SEARCHEDMSDOCCompletedEventHandler(object sender, SEARCHEDMSDOCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SEARCHEDMSDOCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SEARCHEDMSDOCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591